task :twenty_fourteen_season => :environment do
  packers = Team.find_by(name: "Packers")
  seahawks = Team.find_by(name: "Seahawks")
  saints = Team.find_by(name: "Saints")
  falcons = Team.find_by(name: "Falcons")
  vikings = Team.find_by(name: "Vikings")
  rams = Team.find_by(name: "Rams")
  browns = Team.find_by(name: "Browns")
  steelers = Team.find_by(name: "Steelers")
  jaguars = Team.find_by(name: "Jaguars")
  eagles = Team.find_by(name: "Eagles")
  raiders = Team.find_by(name: "Raiders")
  jets = Team.find_by(name: "Jets")
  bengals = Team.find_by(name: "Bengals")
  ravens = Team.find_by(name: "Ravens")
  bills = Team.find_by(name: "Bills")
  bears = Team.find_by(name: "Bears")
  redskins = Team.find_by(name: "Redskins")
  texans = Team.find_by(name: "Texans")
  titans = Team.find_by(name: "Titans")
  chiefs = Team.find_by(name: "Chiefs")
  patriots = Team.find_by(name: "Patriots")
  dolphins = Team.find_by(name: "Dolphins")
  panthers = Team.find_by(name: "Panthers")
  buccaneers = Team.find_by(name: "Buccaneers")
  fortyniners = Team.find_by(name: "49ers")
  cowboys = Team.find_by(name: "Cowboys")
  colts = Team.find_by(name: "Colts")
  broncos = Team.find_by(name: "Broncos")
  giants = Team.find_by(name: "Giants")
  lions = Team.find_by(name: "Lions")
  chargers = Team.find_by(name: "Chargers")
  cardinals = Team.find_by(name: "Cardinals")


#week 1
  Game.create(home_team_id: packers.id, away_team_id: seahawks.id, kickoff: DateTime.parse("2014/9/4 20.30"))
  Game.create(home_team_id: bills.id, away_team_id: bears.id, kickoff: DateTime.parse("2014/9/7 13:00"))
  Game.create(home_team_id: bengals.id, away_team_id: ravens.id, kickoff: DateTime.parse("2014/9/7 13:00"))
  Game.create(home_team_id: browns.id, away_team_id: steelers.id, kickoff: DateTime.parse("2014/9/7 13:00"))
  Game.create(home_team_id: redskins.id, away_team_id: texans.id, kickoff: DateTime.parse("2014/9/7 13:00"))
  Game.create(home_team_id: jaguars.id, away_team_id: eagles.id, kickoff: DateTime.parse("2014/9/7 13:00"))
  Game.create(home_team_id: titans.id, away_team_id: chiefs.id, kickoff: DateTime.parse("2014/9/7 13:00"))
  Game.create(home_team_id: patriots.id, away_team_id: dolphins.id, kickoff: DateTime.parse("2014/9/7 13:00"))
  Game.create(home_team_id: vikings.id, away_team_id: rams.id, kickoff: DateTime.parse("2014/9/7 13:00"))
  Game.create(home_team_id: saints.id, away_team_id: falcons.id, kickoff: DateTime.parse("2014/9/7 13:00"))
  Game.create(home_team_id: raiders.id, away_team_id: jets.id, kickoff: DateTime.parse("2014/9/7 13:00"))
  Game.create(home_team_id: panthers.id, away_team_id: buccaneers.id, kickoff: DateTime.parse("2014/9/7 16:25"))
  Game.create(home_team_id: fortyniners.id, away_team_id: cowboys.id, kickoff: DateTime.parse("2014/9/7 16:25"))
  Game.create(home_team_id: colts.id, away_team_id: broncos.id, kickoff: DateTime.parse("2014/9/7 20:30"))
  Game.create(home_team_id: giants.id, away_team_id: lions.id, kickoff: DateTime.parse("2014/9/8 19:10"))
  Game.create(home_team_id: chargers.id, away_team_id: cardinals.id, kickoff: DateTime.parse("2014/9/8 22:20"))

#week 2
  Game.create(home_team_id: ravens.id, away_team_id: steelers.id, kickoff: DateTime.parse("2014/9/11 20:25"))
  Game.create(home_team_id: panthers.id, away_team_id: lions.id, kickoff: DateTime.parse("2014/9/14 13:00"))
  Game.create(home_team_id: giants.id, away_team_id: cardinals.id, kickoff: DateTime.parse("2014/9/14 13:00"))
  Game.create(home_team_id: redskins.id, away_team_id: jaguars.id, kickoff: DateTime.parse("2014/9/14 13:00"))
  Game.create(home_team_id: bengals.id, away_team_id: falcons.id, kickoff: DateTime.parse("2014/9/14 13:00"))
  Game.create(home_team_id: titans.id, away_team_id: cowboys.id, kicoff: DateTime.parse("2014/9/14 13:00"))
  Game.create(home_team_id: vikings.id, away_team_id: patriots.id, kickoff: DateTime.parse("2014/9/14 13:00"))
  Game.create(home_team_id: browns.id, away_team_id: saints.id, kickoff: DateTime.parse("2014/9/14 13:00"))
  Game.create(home_team_id: bills.id, away_team_id: dolphins.id, kickof: DateTime.parse("2014/9/14 13:00"))
  Game.create(home_team_id: buccaneers.id, away_team_id: rams.id, kickoff: DateTime.parse("2014/9/14 16:05"))
  Game.create(home_team_id: chargers.id, away_team_id: seahawks.id, kickoff: DateTime.parse("2014/9/14 16:05"))
  Game.create(home_team_id: raiders.id, away_team_id: texans.id, kickoff: DateTime.parse("2014/9/14 16:45"))
  Game.create(home_team_id: packers.id, away_team_id: jets.id, kickoff: DateTime.parse("2014/9/14 16:45"))
  Game.create(home_team_id: broncos.id, away_team_id: chiefs.id, kickoff: DateTime.parse("2014/9/14 16:25"))
  Game.create(home_team_id: fortyniners.id, away_team_id: bears.id, kickoff: DateTime.parse("2014/9/14 20:30"))
  Game.create(home_team_id: colts.id, away_team_id: eagles.id, kickoff: DateTime.parse("2014/9/15 20:30")


#week 3
  Game.create(home_team_id: falcons.id, away_team_id: buccaneers.id, kickoff: DateTime.parse("2014/9/18 20:25"))
  Game.create(home_team_id: bengals.id, away_team_id: titans.id, kickoff: DateTime.parse("2014/9/21 13:00"))
  Game.create(home_team_id: bills.id, away_team_id: chargers.id, kickoff: DateTime.parse("2014/9/21 13:00"))
  Game.create(home_team_id: lions.id, away_team_id: packers, kickoff: DateTime.parse("2014/9/21 13:00"))
  Game.create(home_team_id: giants.id, away_team_id: texans.id, kickoff: DateTime.parse("2014/9/21 13:00"))
  Game.create(home_team_id: saints.id, away_team_id: vikings.id, kickoff: DateTime.parse("2014/9/21 13:00"))
  Game.create(home_team_id: browns.id, away_team_id: ravens.id, kickoff: DateTime.parse("2014/9/21 13:00"))
  Game.create(home_team_id: rams.id, away_team_id: cowboys.id, kickoff: DateTime.parse("2014/9/21 13:00"))
  Game.create(home_team_id: jaguars.id, away_team_id: colts.id, kickoff: DateTime.parse("2014/9/21 13:00"))
  Game.create(home_team_id: eagles.id, away_team_id: redskins.id, kickoff: DateTime.parse("2014/9/21 13:00"))
  Game.create(home_team_id: patriots.id, away_team_id: raiders.id, kickoff: DateTime.parse("2014/9/21 13:00"))
  Game.create(home_team_id: cardinals.id away_team_id: fortyniners.id, kickoff: DateTime.parse("2014/9/21 16:05")
  Game.create(home_team_id: dolphins.id, away_team_id: chiefs.id, kickoff: DateTime.parse("2014/9/21 16:25"))
  Game.create(home_team_id: seahawks.id, away_team_id: broncos.id, kickoff: DateTime.parse("2014/9/21 16:25"))
  Game.create(home_team_id: panthers.id, away_team_id: steelers.id, kickoff: DateTime.parse("2014/9/21 20:30"))
  Game.create(home_team_id: jets.id, away_team_id: bears.id, kickoff: DateTime.parse("2014/9/22 20:30"))

#week 4
  Game.create(home_team_id: redskins.id, away_team_id: giants.id, kickoff: DateTime.parse("2014/9/25 20:25"))
  Game.create(home_team_id: jets.id, away_team_id: lions.id, kickoff: DateTime.parse("2014/9/28 13:00"))
  Game.create(home_team_id: colts.id, away_team_id: titans, kickoff: DateTime.parse("2014/9/28 13:00"))
  Game.create(home_team_id: steelers.id, away_team_id: buccaneers.id, kickoff: DateTime.parse("2014/9/28 13:00"))
  Game.create(home_team_id: ravens.id, away_team_id: panthers.id, kickoff: DateTime.parse("2014/9/28 13:00"))
  Game.create(home_team_id: texans.id, away_team_id: bills.id, kickoff: DateTime.parse("2014/9/28 13:00"))





end