# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


bills = Team.create(name: "Bills", city: "Buffalo", logo: "buffalo_bills.png")
patriots = Team.create(name: "Patriots", city: "New England", logo: "new_england_patriots.png")
jets = Team.create(name: "Jets", city: "New York", logo: "newyork_jets.png")
dolphins = Team.create(name: "Dolphins", city: "Miami", logo: "miami_dolphins.png")
bengals = Team.create(name: "Bengals", city: "Cincinnati", logo: "cincinnati_bengals.png")
ravens = Team.create(name: "Ravens", city: "Baltimore", logo: "baltimore_ravens.png")
steelers = Team.create(name: "Steelers", city: "Pittsburg", logo: "pittsburg_steelers.png")
browns = Team.create(name: "Browns", city: "Cleveland", logo: "cleveland_browns.png")
texans = Team.create(name: "Texans", city: "Houston", logo: "houston_texans.png")
colts = Team.create(name: "Colts", city: "Indianapolis", logo: "indianapolis_colts.png")
titans = Team.create(name: "Titans", city: "Tennessee", logo: "tennessee_titans.png")
jaguars = Team.create(name: "Jaguars", city: "Jacksonville", logo: "jacksonville_jaguars.png")
broncos = Team.create(name: "Broncos", city: "Denver", logo: "denver_broncos.png")
chargers = Team.create(name: "Chargers", city: "San Diego", logo: "sandiego_chargers.png")
chiefs = Team.create(name: "Chiefs", city: "Kansas City", logo: "kansascity_cheifs.png")
raiders = Team.create(name: "Raiders", city: "Oakland", logo: "oakland_raiders.png")
eagles = Team.create(name: "Eagles", city: "Philadelphia", logo: "philadelphia_eagles.png")
cowboys = Team.create(name: "Cowboys", city: "Dallas", logo: "dallas_cowboys.png")
giants = Team.create(name: "Giants", city: "New York", logo: "newyork_giants.png")
redskins = Team.create(name: "Redskins", city: "Washington", logo: "washington_redskins.png")
lions = Team.create(name: "Lions", city: "Detroit", logo: "detroit_lions.png")
bears = Team.create(name: "Bears", city: "Chicago", logo: "chicago_bears.png")
vikings = Team.create(name: "Vikings", city: "Minnesota", logo: "minnesota_vikings.png")
packers = Team.create(name: "Packers", city: "Green Bay", logo: "greenbay_packers.png")
falcons = Team.create(name: "Falcons", city: "Atlanta", logo: "atlanta_falcons.png")
panthers = Team.create(name: "Panthers", city: "Carolina", logo: "carolina_panthers.png")
saints = Team.create(name: "Saints", city: "New Orleans", logo: "neworleans_saints.png")
buccaneers = Team.create(name: "Buccaneers", city: "Tampa Bay", logo: "tampabay_buccaneers.png")
cardinals = Team.create(name: "Cardinals", city: "Arizona", logo: "arizona_cardinals.png")
rams = Team.create(name: "Rams", city: "St. Louis", logo: "stlouis_rams.png")
fortyniners = Team.create(name: "49ers", city: "San Francisco", logo: "sanfrancisco_49ers.png")
seahawks = Team.create(name: "Seahawks", city: "Seattle", logo: "seattle_seahawks.png")