# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


bills = Team.create(name: "Bills", city: "Buffalo", logo: "NFL_Bills.gif")
patriots = Team.create(name: "Patriots", city: "New England", logo: "NFL_Patriots.gif")
jets = Team.create(name: "Jets", city: "New York", logo: "NFL_Jets.gif")
dolphins = Team.create(name: "Dolphins", city: "Miami", logo: "nfl-mia-98t.gif")
bengals = Team.create(name: "Bengals", city: "Cincinnati", logo: "nfl-cin-94t.gif")
ravens = Team.create(name: "Ravens", city: "Baltimore", logo: "NFL_Ravens.gif")
steelers = Team.create(name: "Steelers", city: "Pittsburg", logo: "NFL_Steelers.gif")
browns = Team.create(name: "Browns", city: "Cleveland", logo: "NFL_Browns.gif")
texans = Team.create(name: "Texans", city: "Houston", logo: "NFL_Texans.gif")
colts = Team.create(name: "Colts", city: "Indianapolis", logo: "NFL_Colts.gif")
titans = Team.create(name: "Titans", city: "Tennessee", logo: "NFL_Titans.gif")
jaguars = Team.create(name: "Jaguars", city: "Jacksonville", logo: "NFL_Jaguars.gif")
broncos = Team.create(name: "Broncos", city: "Denver", logo: "NFL_Broncos.gif")
chargers = Team.create(name: "Chargers", city: "San Diego", logo: "sd_Chargers.gif")
chiefs = Team.create(name: "Chiefs", city: "Kansas City", logo: "NFL_Chiefs.gif")
raiders = Team.create(name: "Raiders", city: "Oakland", logo: "NFL_Raiders.gif")
eagles = Team.create(name: "Eagles", city: "Philadelphia", logo: "NFL_Eagles.gif")
cowboys = Team.create(name: "Cowboys", city: "Dallas", logo: "NFL_Cowboys.gif")
giants = Team.create(name: "Giants", city: "New York", logo: "NFL_Giants.gif")
redskins = Team.create(name: "Redskins", city: "Washington", logo: "NFL_Redskins.gif")
lions = Team.create(name: "Lions", city: "Detroit", logo: "NFL_Lions.gif")
bears = Team.create(name: "Bears", city: "Chicago", logo: "NFL_Bears.gif")
vikings = Team.create(name: "Vikings", city: "Minnesota", logo: "NFL_Vikings.gif")
packers = Team.create(name: "Packers", city: "Green Bay", logo: "NFL_Packers.gif")
falcons = Team.create(name: "Falcons", city: "Atlanta", logo: "NFL_Falcons.gif")
panthers = Team.create(name: "Panthers", city: "Carolina", logo: "NFL_Panthers.gif")
saints = Team.create(name: "Saints", city: "New Orleans", logo: "NFL_Saints.gif")
buccaneers = Team.create(name: "Buccaneers", city: "Tampa Bay", logo: "NFL_Buccaneers.gif")
cardinals = Team.create(name: "Cardinals", city: "Arizona", logo: "NFL_Cardinals.gif")
rams = Team.create(name: "Rams", city: "St. Louis", logo: "NFL_Rams.gif")
fortyniners = Team.create(name: "49ers", city: "San Francisco", logo: "NFL_49ers.gif")
seahawks = Team.create(name: "Seahawks", city: "Seattle", logo: "Seahawks.gif")
